Cross validation allows to evaluate the performance of a model. Definetly this can be achieved by training and testing the model.There are various ways to do this.
1. Use all available data for training and test on same dataset.-obviously this is not good way because model has seen all the data already definately it will perform well on them
2. Split available dataset into training and test sets. - This is good but this also has problem if unseen data is totally different concept from seen data.
3. K fold cross validation - Where data is divided into equal folds(suppose we have 100 samples then 5 folds each fold 20 samples).we will train model in iterations in each iteration 1 fold is made test set. iterations are repeated untill each fold once becomes test set.
In the below we are checking models performce for digits dataset

In [16]:
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [18]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9425925925925925

In [19]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9777777777777777

In [20]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9574074074074074

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model,X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [27]:
get_score(SVC(), X_train, y_train, X_test, y_test)

0.9777777777777777

In [28]:
from sklearn.model_selection import StratifiedKFold #to get same distribution of classes in each fold
folds = StratifiedKFold(n_splits=3)

In [35]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, y_train, X_test, y_test))
    scores_svm.append(get_score(SVC(), X_train, y_train, X_test, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, y_train, X_test, y_test))

c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [36]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [37]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [38]:
scores_rf

[0.9282136894824707, 0.9565943238731218, 0.9115191986644408]

In [39]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target)

c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [42]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.91944444, 0.91944444, 0.94986072, 0.95821727, 0.92200557])

In [50]:
from sklearn.datasets import load_iris
iris = load_iris()
from sklearn.model_selection import cross_val_score
L=cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
print(L)
print(np.mean(L))

[0.98 0.96 0.98]
0.9733333333333333


c:\Users\shree\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [51]:
s = cross_val_score(SVC(), iris.data, iris.target, cv=3)
print(s)
print(np.mean(s))

[0.96 0.98 0.94]
0.96


In [53]:
R = cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)
print(R)
print(np.average(R))

[0.98 0.94 0.96]
0.96
